config/routes.rb
Rails.application.routes.draw do
  resources :recipe_ingredients
  # resources :likes
  resources :ingredients
  resources :recipes
  resources :users

  delete "/sessions/logout", to: 'sessions#logout', as: 'logout'
  get "/sessions/new", to: 'sessions#new', as: 'new_login'
  post '/sessions/login', to: 'sessions#login', as: 'login'

  post '/likes', to: 'likes#create', as: 'new_like'

  get '/users/:id/profile', to: 'users#profile', as: 'profile'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    has_many :recipe_ingredients
    has_many :recipes, through: :recipe_ingredients
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :recipe 

    validates :recipe_id, uniqueness: {scope: :user_id}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients 
    has_many :likes 
    has_many :users, through: :likes 
    belongs_to :user
    
    accepts_nested_attributes_for :recipe_ingredients

    def self.search(search)
        if search
            ingredient = Ingredient.find_by(name: search)
            if ingredient
               ingredient.recipes
            else
                Recipe.all
            end
        else
            Recipe.all
        end
    end

end

app/models/recipe_ingredient.rb
class RecipeIngredient < ApplicationRecord
    belongs_to :recipe 
    belongs_to :ingredient 
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes
    has_many :recipes, through: :likes 
    has_many :created_recipes, foreign_key: "user_id", class_name: "Recipe"

    has_secure_password 

    validates :age, numericality: {greater_than_or_equal_to: 21}

    # validates_numericality_of :stock_qty, :greater_than_or_equal_to => 0
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :find_current_user
    before_action :authorized

  def find_current_user
    @current_user = User.find_by(id: cookies[:user_id])
  end 


  def authorized
    redirect_to new_user_path unless @current_user
  end 


end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController

    def index
        @ingredients = Ingredient.all 
    end

    def show
        @ingredient = Ingredient.find(params[:id])
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

    def create
        # @user = User.find(cookies[:user_id])
        @recipe = Recipe.find(params[:recipe_id])
        @new_like = Like.create(user_id: @current_user.id, recipe_id: @recipe.id)
        redirect_to recipe_path(@recipe.id)
    end

end

app/controllers/recipe_ingredients_controller.rb
class RecipeIngredientsController < ApplicationController
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

    skip_before_action :authorized, only: [:index]

    def index
        @recipes = Recipe.search(params[:search])
    end


    def show 
        @recipe = Recipe.find(params[:id])
    end 

    def edit 
        @recipe = Recipe.find(params[:id])
        
        if @recipe.user.id == @current_user.id
            render :edit
        else
             redirect_to recipe_path(@recipe) 
             flash[:error] = 'You can only edit your own recipe!'
        end  
      
    end 

    def new 
        @recipe = Recipe.new 
       
        params[:ingredient_count].to_i.times {@recipe.recipe_ingredients.build}
    end 

    def create
        
        @recipe = Recipe.create(recipe_params)
        
        redirect_to recipe_path(@recipe.id)
        
    end


    def destroy 
        @recipe = Recipe.find(params[:id])
        if @recipe.user.id == @current_user.id
            @recipe.destroy 
            redirect_to profile_path(@current_user)
        else
             redirect_to recipe_path(@recipe) 
             flash[:error] = 'You can only delete your own recipe!'
        end 
    end 
    
      
    def update 
        @recipe = Recipe.find(params[:id])
        @recipe.update(recipe_params)
        redirect_to recipe_path(@recipe)
    end 
  
  

    private

    def recipe_params
        params.require(:recipe).permit(:title, :user_id, :image, :api_id, recipe_ingredients_attributes: [:ingredient_id, :measurement])
    end

 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :login]
   
    
      def logout
        cookies.delete(:user_id)
        redirect_to new_user_path
      end 
    
      def new
      end
    
      def login
        user = User.find_by(name: params[:session][:name])
    
        if user && user.authenticate(params[:session][:password])
          cookies[:user_id] = user.id
          redirect_to recipes_path
        else
          flash[:errors] = "Username or Password does not match" 
          redirect_to new_login_path
        end 
      end 
    
    end
    

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :authorized, only: [:new, :create]


    def index 
        @users = User.all 
    end

    def show 
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end
    
    def create
            user = User.create(user_params)
        
            if user.valid?
              cookies[:user_id] = user.id
              redirect_to users_path
            else
              flash[:errors] = user.errors.full_messages
              redirect_to new_user_path 
            end 
         
    end

    def profile
        if @current_user.valid?
            render :profile 
        else
            redirect_to login_path 
        end
    end


    private 

    def user_params 
        params.require(:user).permit(:name, :age, :password, :image)
    end 

end

app/helpers/alcohols_helper.rb
module AlcoholsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/recipe_alcohols_helper.rb
module RecipeAlcoholsHelper
end

app/helpers/recipe_ingredients_helper.rb
module RecipeIngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ingredients/index.html.erb
<h1>Ingredients</h1>

<% @ingredients.each do |i| %>
    <%= link_to i.name, ingredient_path(i) %>
<% end %>

app/views/ingredients/show.html.erb
<h1> <%= @ingredient.name %> </h1> 

<h3> Recipes: <% @ingredient.recipes.each do |recipe| %> </h3> 
    <li> <%= link_to recipe.title, recipe_path(recipe) %> </li> 
    <%end%> 

app/views/recipes/_form.html.erb
  <div class = "form">
  <%= form_for  @recipe do |f| %>
    <div class = "form-input">
    <%= f.label :title %>
    <%= f.text_field :title %> <br>
    <br>
    <br>
    </div>

    <div class = "form-input">
   
     <p>Please Enter Image URL: <%# f.label :image %><%= f.text_field :image %></p>
     
    <br>
    <br>
     </div>
    <%= f.hidden_field :user_id, value: @current_user.id  %>
 

  <%= f.fields_for :recipe_ingredients do |ff| %>
  <div class = "form-input">
  <%= ff.label :ingredient_id %> 
  <%= ff.collection_select :ingredient_id, Ingredient.all, :id, :name %> 
  <%= ff.label :measurement %>
  <%= ff.text_field :measurement %><br>
  <%# ff.collection_check_boxes :ingredient_id, Ingredient.all, :id, :name %> <br>

  <% end %>
   </div>
  <%= f.submit class: "btn" %>

<% end %>
</div>



  

app/views/recipes/edit.html.erb
<h1 id="Heading"> My Recipe </h1> 


<%= render 'form' %>

app/views/recipes/index.html.erb
<div class = "index-page-container">
    <div>
        <h1 id = 'Heading' >All Recipes</h1>

        <div class = "form">
            <h4>Search by Ingredient:</h4>
            <%= form_tag(recipes_path, method: :get) do %>
                <%= text_field_tag(:search) %>
                <%= submit_tag ("Search"), class: "btn" %>
            <% end %>
        </div>
        <div class="form">
        <h4>Create New Recipe: </h4>
            <%= form_tag(new_recipe_path, method: :get) do %>
                <%= label_tag("Please enter number of ingredients") %>
                <%= text_field_tag(:ingredient_count) %>
                <%= submit_tag ("Create"), class: "btn" %>
            <% end %>
        </div>
    </div>
    <div class='index-container'>
        <% @recipes.each do |recipe|%>
        
            <div class='index-tile'>
            <%= link_to recipe.title, recipe_path(recipe) %> <br>
            <%= link_to recipe_path(recipe) do %>
                <img class = "index-img" src="<%= recipe.image%>">
            <% end %>
            </div>
        

        <% end %>
    </div>
</div> 

app/views/recipes/new.html.erb
<h1 id="Heading"> My Recipe </h1> 

<%= render 'form' %>
 





   

app/views/recipes/show.html.erb
<br>
<br>
<br>

 

<div class = "show_container">
  <div class = "show-tile1">
    <h1 id = "Heading"> <%= @recipe.title %> <h1> 
    <h4 id = "Heading"> Creator: <%= link_to @recipe.user.name, user_path(@recipe.user.id)%></h4>
  </div>
  <div class = "show-tile1">
    <div id = "likes">
      <h5>Likes: <%= @recipe.likes.count %> </h5> 
      <%= button_to 'Like', {:controller => "likes", :action => "create", :recipe_id => @recipe.id},  method: :post, class: "button1" %>

    </div>
  </div>
  <div class = "show-tile1">

      <img class = "show-img" src="<%= @recipe.image %>"  width="200" height="300" >

  </div>
  <div class = "show-tile1">
    <h2 id = "ingred-header">Ingredients: </h2>
      <ul class = "list"> <% @recipe.recipe_ingredients.each do |i| %> 
    <li class = "item"> <%= i.measurement %> <%= link_to i.ingredient.name, ingredient_path(i.ingredient_id) %> </li> <br>
    </ul>
  <%end%> 
  </div>  
</div>

app/views/users/index.html.erb
<h1 id = "Heading" >User Directory</h1>

<div class='index-container'>

<% @users.each do |user|%>
   <div class = "index-tile">
      <h2><%= link_to user.name, user_path(user) %></h2>
      <p >Total Recipes: <%= user.created_recipes.count %></p>
      <img class = "index-img" src="<%= user.image %>" >
   </div> 
 <% end %>
 </div>

app/views/users/new.html.erb
<h1 id = "Heading">Sign Up</h1>

<div class = "form">

<% if flash[:errors] %>
    <% flash[:errors].each do |error|%>
        <%= error %>
    <% end %>
<% end %>

<%= form_for @user do |f| %>
    <div class = 'form-input'>
    <%= f.label :name %>
    <%= f.text_field :name %> 
    </div>
    <br>
    <div class = 'form-input'>
    <%= f.label :age %>
    <%= f.text_field :age %> 
    </div> 
    <br>
    <div class = 'form-input'>
    <%= f.label :password %>
    <%= f.password_field :password %> 
    </div>
    <br>
    <%= f.hidden_field :image, value: "https://robohash.org/#{Faker::Avatar.image}.png/?set=set2" %>

    <%= f.submit class: "btn" %>
    <%end%> 

 </div> 

app/views/users/profile.html.erb
<div class = "page-container">
<br>
<div class = "profile-container1">
<h1 id="Heading"> Hello, <%= @current_user.name %> </h1> 
<h2> Age: <%= @current_user.age %> </h2> 
<img src="<%= @current_user.image %>" alt="">
</div>
<div class = "profile-container2">
<h2> My Creations: <% @current_user.created_recipes.each do |recipe|%> </h2> 
    <img src="<%= recipe.image %>" width="250" height="300" > <br>
    <li> <%= link_to recipe.title, recipe_path(recipe) %> <br>  <%=  button_to 'Edit', edit_recipe_path(recipe), method: :get, class: "button1" %>  <%=  button_to 'Delete', recipe_path(recipe), method: :delete, class: "button1"%>  </li>
    <br>
    <br>
<% end %>
</div>
 <div class = "profile-container2">
<h2>Liked Recipes</h2>
<% @current_user.recipes.each do |recipe| %>
    <%= recipe.title %> <br>
  
<% end %>
</div>
</div>


 
    

app/views/users/show.html.erb
<div class = "page-container">

<div class = "profile-container1">
<h1> <%= @user.name %> </h1> 

<h2> Age: <%= @user.age %> </h2> 

<img src="<%= @user.image %>" >
</div>

<div class = "profile-container2">
<h4> Creations: <% @user.created_recipes.each do |recipe|%> </h4> 
    <img src="<%= recipe.image %>" width="250" height="300">
    <li> <%= link_to recipe.title, recipe_path(recipe) %> </li>
<% end %>
</div>
<div class = "profile-container2">
<h4>Liked Recipes</h4>
<% @user.recipes.each do |recipe| %>
    <%= recipe.title %> <br>
  </div>
<% end %>

</div>